// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjSztWKm3wSzOyV5Y6zowUFNEaP1HNyj8',
    appId: '1:1058377040322:web:f8e4749abfac689991165b',
    messagingSenderId: '1058377040322',
    projectId: 'wedrive008',
    authDomain: 'wedrive008.firebaseapp.com',
    databaseURL: 'https://wedrive008-default-rtdb.firebaseio.com',
    storageBucket: 'wedrive008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4JLgt0BtFVYKWXjN8OI7giD_eYli6bM',
    appId: '1:1058377040322:android:a3c0660331494d6191165b',
    messagingSenderId: '1058377040322',
    projectId: 'wedrive008',
    databaseURL: 'https://wedrive008-default-rtdb.firebaseio.com',
    storageBucket: 'wedrive008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD77pFzDJjzDN1LPxR_tmMCMit9V-iARio',
    appId: '1:1058377040322:ios:17fb123f0908822291165b',
    messagingSenderId: '1058377040322',
    projectId: 'wedrive008',
    databaseURL: 'https://wedrive008-default-rtdb.firebaseio.com',
    storageBucket: 'wedrive008.appspot.com',
    iosBundleId: 'com.example.users',
  );
}
